version: '2.4'

services:
  proxy: 
    image: nginx:latest
    container_name: proxy
    depends_on:
      dmoj-judge:
        condition: service_started
    volumes:
      - $PWD/proxy/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/proxy/docker_calibre_edf_fr.key:/cert.key
      - $PWD/proxy/docker_calibre_edf_fr.pem:/cert.pem
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    restart: always

  dmoj-site:
    build: ./site
    #image: dmoj-site
    depends_on:
      dmoj-mysql:
        condition: service_healthy
    container_name: dmoj-site
    volumes:
      - /local00/docker-data/dmoj/logs:/dmoj/logs
    networks:
      - default
      - isolated_nw
    expose:
      - "80"
    hostname:
      dmoj-site
    healthcheck:
      test: ["CMD", "sleep", "2m"]
      interval: 10s
      timeout: 150s
      retries: 1
    restart: always

  dmoj-mysql:
    image: mysql/mysql-server:5.7
    container_name: dmoj-mysql
    volumes:
      - /local00/docker-data/dmoj/mysql:/var/lib/mysql
    networks:
      isolated_nw:
        ipv4_address: 172.25.3.3
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "dmoj"
      MYSQL_USER: "dmoj"
      MYSQL_PASSWORD: "dmoj"
      MYSQL_DATABASE: "dmoj"
    ports:
     - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  dmoj-judge:
    build: ./judge
    #image: dmoj-judge
    depends_on:
      dmoj-site:
        condition: service_healthy
    container_name: dmoj-judge
    privileged: true
    volumes:
      - /local00/docker-data/dmoj/problems:/problems
    entrypoint: dmoj dmoj-site the_judge 0123456789 -c /dmoj-judge-docker/judge.yml
    networks:
      - default
    restart: always

networks:
  isolated_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
